#pragma once
#include <stdio.h>
#include <cstdlib>
#include <conio.h>
#include <memory>
#include <thread>
#include <chrono>
#include <cmath>
#include <iostream>
#include <stdexcept>
#ifdef GB_PLATFORM_WINDOWS
#include <Windows.h>
#include <intrin.h>
#endif // GB_PLATFORM_WINDOWS
#include "glad/glad.h"
#include "GLFW/glfw3.h"
#include "imgui.h"
#include "backends/imgui_impl_glfw.h"
#include "backends/imgui_impl_opengl3.h"